import path from "node:path";
import { describe, expect, it } from "vitest";
import { CLI_DISPLAY_NAME, SINSCRIBE_VERSION } from "../src/constants.js";
import {
  buildDocsExportMarkdown,
  DOCS_EXPORT_FILENAME,
  getDocsExportPath,
} from "../src/domain/docs-export.js";

describe("getDocsExportPath", () => {
  it("joins the fixed filename onto the repo root", () => {
    expect(getDocsExportPath("/repo")).toBe(
      path.join("/repo", "PROJECT_DOCUMENTATION.md"),
    );
    expect(DOCS_EXPORT_FILENAME).toBe("PROJECT_DOCUMENTATION.md");
  });

  it("never collides with a lowercase documentation.md on case-insensitive filesystems", () => {
    // Tripwire: macOS filesystems are case-insensitive, so an export named
    // DOCUMENTATION.md would silently overwrite a repo's own documentation.md.
    expect(DOCS_EXPORT_FILENAME.toLowerCase()).not.toBe("documentation.md");
  });
});

describe("buildDocsExportMarkdown", () => {
  it("emits the metadata comment and the trimmed content", () => {
    expect(
      buildDocsExportMarkdown({
        content: "# Project — Documentation\n\n## Overview\n\n",
        generatedAt: new Date("2026-07-09T12:00:00.000Z"),
      }),
    ).toBe(
      [
        `<!-- Generated by ${CLI_DISPLAY_NAME} v${SINSCRIBE_VERSION} on 2026-07-09T12:00:00.000Z -->`,
        "",
        "# Project — Documentation",
        "",
        "## Overview",
        "",
      ].join("\n"),
    );
  });
});
