import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { CLI_DISPLAY_NAME, SINSCRIBE_VERSION } from "../src/constants.js";
import {
  buildHandoffMarkdown,
  getHandoffPath,
  HANDOFF_FILENAME,
  loadHandoff,
  parseHandoff,
} from "../src/domain/handoff-export.js";
import { makeTempDir, removeDir } from "./git-fixture.js";

const BODY = [
  "## Where things stand",
  "- The uploader retries but does not back off.",
  "",
  "## Next steps",
  "1. Add exponential backoff.",
].join("\n");

describe("getHandoffPath", () => {
  it("joins the fixed filename onto the repo root", () => {
    expect(getHandoffPath("/repo")).toBe(path.join("/repo", "HANDOFF.md"));
    expect(HANDOFF_FILENAME).toBe("HANDOFF.md");
  });
});

describe("buildHandoffMarkdown", () => {
  const input = {
    projectName: "sinscribe",
    branch: "feature/retry-uploads",
    ticket: "ABC-123",
    body: BODY,
    generatedAt: new Date("2026-08-04T18:22:10.412Z"),
  };

  it("stamps metadata, the title, and the date around the model's body", () => {
    expect(buildHandoffMarkdown(input)).toBe(
      [
        `<!-- Generated by ${CLI_DISPLAY_NAME} v${SINSCRIBE_VERSION} on 2026-08-04T18:22:10.412Z -->`,
        "<!-- Branch: feature/retry-uploads · Ticket: ABC-123 -->",
        "",
        "# sinscribe — Session Handoff",
        "",
        "> Reflects the current state of this branch, not an accumulated history.",
        "> Regenerated at the end of each session.",
        "",
        "## Last updated",
        "2026-08-04",
        "",
        BODY,
        "",
      ].join("\n"),
    );
  });

  it("labels a missing ticket as none", () => {
    expect(buildHandoffMarkdown({ ...input, ticket: null })).toContain(
      "Ticket: none",
    );
  });
});

describe("parseHandoff", () => {
  it("round-trips the branch and body written by buildHandoffMarkdown", () => {
    const parsed = parseHandoff(
      buildHandoffMarkdown({
        projectName: "sinscribe",
        branch: "feature/retry-uploads",
        ticket: "ABC-123",
        body: BODY,
      }),
    );

    expect(parsed.branch).toBe("feature/retry-uploads");
    expect(parsed.body).toContain("# sinscribe — Session Handoff");
    expect(parsed.body).toContain("## Where things stand");
    expect(parsed.body).not.toContain("<!--");
  });

  it("reads a hand-written file with no metadata as branchless", () => {
    const parsed = parseHandoff(`# Notes\n\n${BODY}\n`);

    expect(parsed.branch).toBeNull();
    expect(parsed.body).toContain("# Notes");
  });

  it("keeps a comment that appears inside the body", () => {
    const parsed = parseHandoff(
      [
        "<!-- Branch: main · Ticket: none -->",
        "",
        "# Title",
        "",
        "<!-- note -->",
        "",
        BODY,
      ].join("\n"),
    );

    expect(parsed.branch).toBe("main");
    expect(parsed.body).toContain("<!-- note -->");
  });
});

describe("loadHandoff", () => {
  let repo: string;

  beforeEach(async () => {
    repo = await makeTempDir("sinscribe-handoff-");
  });

  afterEach(async () => {
    await removeDir(repo);
  });

  it("returns null without a repo root and without a file", async () => {
    expect(await loadHandoff(null)).toBeNull();
    expect(await loadHandoff(repo)).toBeNull();
  });

  it("returns null for a whitespace-only file rather than an empty body", async () => {
    await writeFile(getHandoffPath(repo), "\n   \n", "utf8");

    expect(await loadHandoff(repo)).toBeNull();
  });

  it("returns null for a file holding only metadata comments", async () => {
    await writeFile(
      getHandoffPath(repo),
      "<!-- Branch: main · Ticket: none -->\n",
      "utf8",
    );

    expect(await loadHandoff(repo)).toBeNull();
  });

  it("reads the branch and body back", async () => {
    await writeFile(
      getHandoffPath(repo),
      buildHandoffMarkdown({
        projectName: "sinscribe",
        branch: "feature/login",
        ticket: null,
        body: BODY,
      }),
      "utf8",
    );

    const parsed = await loadHandoff(repo);

    expect(parsed?.branch).toBe("feature/login");
    expect(parsed?.body).toContain("## Where things stand");
  });

  it("propagates a non-ENOENT read failure instead of hiding it", async () => {
    // A directory where the file should be: read fails with EISDIR, not ENOENT.
    await mkdir(getHandoffPath(repo));

    await expect(loadHandoff(repo)).rejects.toThrow();
  });
});
