import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  assembleHandoffBody,
  buildIndexMarkdown,
  buildLoopPrompt,
  buildPlanDocMarkdown,
  computeCoverage,
  computeProgress,
  computeStageViews,
  countCheckpoints,
  extractLog,
  extractPlanDocBody,
  getPlanDir,
  getPlanDirRel,
  hashDoc,
  nextStage,
  parseIndex,
  parseRequirements,
  parseTasks,
  type PlanIndex,
  type PlanStageId,
  preserveTaskState,
  renderStatusZone,
  replaceStatusZone,
  STATUS_ZONE_END,
  STATUS_ZONE_START,
} from "../src/domain/plan-docs.js";

const REQUIREMENTS = [
  "## Objective & users",
  "Let users reset a password.",
  "",
  "## Functional requirements",
  "",
  "### REQ-1: Request a reset link",
  "- AC-1.1: WHEN a known email is submitted THE SYSTEM SHALL send a link",
  "- **AC-1.2**: WHEN an unknown email is submitted THE SYSTEM SHALL respond identically",
  "",
  "### **REQ-2** — Expire links",
  "- AC-2.1: Links expire after 30 minutes",
  "",
  "## Out of scope",
  "- AC-9.9: not a real criterion, outside any REQ",
].join("\n");

const TASKS = [
  "## Phase 1: Reset request",
  "",
  "- [x] T-1: Add reset token table",
  "  - Implements: AC-2.1",
  "  - Depends on: none",
  "  - Files: `src/db/schema.ts`, `src/db/migrate.ts`",
  "  - Acceptance: table exists with expiry column",
  "  - Verify: `pnpm test db`",
  "  - Size: S",
  "- [ ] **T-2**: Send reset email",
  "  - Implements: AC-1.1, AC-1.2",
  "  - Depends on: T-1",
  "  - Files: src/auth/reset.ts",
  "  - Verify: `pnpm test auth`",
  "  - Size: M",
  "- [ ] Checkpoint: reset flow works end to end",
  "",
  "## Coverage matrix",
  "| AC | Tasks |",
].join("\n");

describe("plan paths", () => {
  it("derives a sanitized directory per branch", () => {
    expect(getPlanDirRel("feat/reset password")).toBe(
      ".sinscribe/specs/feat-reset-password",
    );
    expect(getPlanDir("/repo", "feat/x")).toBe(
      path.join("/repo", ".sinscribe", "specs", "feat-x"),
    );
  });
});

describe("plan document framing", () => {
  it("wraps the body with metadata, title and nav, and extracts it back", () => {
    const markdown = buildPlanDocMarkdown({
      stage: "design",
      branch: "feat/x",
      feature: "Password reset\nmore detail",
      body: "## Overview\nHello",
      generatedAt: new Date("2026-10-07T00:00:00.000Z"),
    });

    expect(markdown).toContain("# Design — Password reset");
    expect(markdown).toContain("[Requirements](requirements.md)");
    expect(markdown).toContain("**Design**");
    expect(markdown).toContain("[Loop prompt](loop-prompt.md)");
    expect(extractPlanDocBody(markdown)).toBe("## Overview\nHello");
  });

  it("falls back gracefully when a human deleted the body markers", () => {
    const raw = [
      "<!-- Generated by X -->",
      "",
      "# Design — Thing",
      "",
      "> [Index](index.md) · **Design**",
      "",
      "## Overview",
      "Body",
    ].join("\n");

    expect(extractPlanDocBody(raw)).toBe("## Overview\nBody");
  });

  it("hashes ignore CRLF and, for tasks, checkbox progress", () => {
    expect(hashDoc("design", "a\r\nb")).toBe(hashDoc("design", "a\nb"));
    expect(hashDoc("tasks", "- [x] T-1: a")).toBe(
      hashDoc("tasks", "- [ ] T-1: a"),
    );
    expect(hashDoc("design", "- [x] a")).not.toBe(hashDoc("design", "- [ ] a"));
  });
});

describe("parseRequirements", () => {
  it("reads REQ headings and their AC bullets, tolerating bold", () => {
    const reqs = parseRequirements(REQUIREMENTS);

    expect(reqs.map((req) => req.id)).toEqual(["REQ-1", "REQ-2"]);
    expect(reqs[0].acs.map((ac) => ac.id)).toEqual(["AC-1.1", "AC-1.2"]);
    expect(reqs[1].title).toBe("Expire links");
    expect(reqs[1].acs).toEqual([
      { id: "AC-2.1", text: "Links expire after 30 minutes" },
    ]);
  });
});

describe("parseTasks", () => {
  it("reads tasks, state and fields, and skips checkpoints", () => {
    const tasks = parseTasks(TASKS);

    expect(tasks.map((task) => [task.id, task.done])).toEqual([
      ["T-1", true],
      ["T-2", false],
    ]);
    expect(tasks[0]).toMatchObject({
      implements: ["AC-2.1"],
      dependsOn: [],
      files: ["src/db/schema.ts", "src/db/migrate.ts"],
      verify: "pnpm test db",
      size: "S",
    });
    expect(tasks[1].implements).toEqual(["AC-1.1", "AC-1.2"]);
    expect(tasks[1].dependsOn).toEqual(["T-1"]);
    expect(countCheckpoints(TASKS)).toEqual({ total: 1, done: 0 });
  });
});

describe("computeCoverage", () => {
  it("is clean when every AC is implemented", () => {
    const report = computeCoverage(
      parseRequirements(REQUIREMENTS),
      parseTasks(TASKS),
    );

    expect(report.errors).toEqual([]);
    expect(report.uncoveredAcs).toEqual([]);
    expect(report.totalAcs).toBe(3);
  });

  it("errors on unknown refs, missing deps, duplicates and cycles", () => {
    const tasks = parseTasks(
      [
        "- [ ] T-1: a",
        "  - Implements: AC-7.1",
        "  - Depends on: T-2",
        "  - Verify: x",
        "- [ ] T-2: b",
        "  - Implements: AC-1.1",
        "  - Depends on: T-1, T-9",
        "  - Verify: x",
        "- [ ] T-2: dup",
      ].join("\n"),
    );
    const report = computeCoverage(parseRequirements(REQUIREMENTS), tasks);

    expect(report.errors).toEqual(
      expect.arrayContaining([
        "T-2 is defined more than once in tasks.md",
        "T-1 implements AC-7.1, which requirements.md lacks",
        "T-2 depends on T-9, which does not exist",
      ]),
    );
    expect(report.errors.some((error) => error.includes("cycle"))).toBe(true);
    expect(report.uncoveredAcs).toEqual(["AC-1.2", "AC-2.1"]);
  });

  it("warns on oversized tasks and missing verify", () => {
    const tasks = parseTasks(
      ["- [ ] T-1: big", "  - Implements: AC-1.1", "  - Size: L"].join("\n"),
    );
    const { warnings } = computeCoverage(
      parseRequirements(REQUIREMENTS),
      tasks,
    );

    expect(warnings).toEqual(
      expect.arrayContaining([
        "T-1 has no Verify command",
        "T-1 is too large (L) — split it",
      ]),
    );
  });
});

describe("preserveTaskState", () => {
  it("keeps checkmarks by id and reports dropped done tasks", () => {
    const previous = parseTasks(
      ["- [x] T-1: a", "- [x] T-3: gone", "- [ ] T-2: b"].join("\n"),
    );
    const { markdown, dropped } = preserveTaskState(
      previous,
      ["- [ ] T-1: a renamed", "- [ ] T-2: b"].join("\n"),
    );

    expect(markdown).toBe(["- [x] T-1: a renamed", "- [ ] T-2: b"].join("\n"));
    expect(dropped).toEqual(["T-3"]);
  });
});

describe("computeProgress", () => {
  it("matches task ids in commit subjects and reports inconsistencies", () => {
    const tasks = parseTasks(TASKS);
    const progress = computeProgress(parseRequirements(REQUIREMENTS), tasks, [
      { sha: "bbb", subject: "feat: send email [T-2]" },
      { sha: "aaa", subject: "feat: token table [T-1]" },
      { sha: "ccc", subject: "chore: typo [T-8]" },
      { sha: "ddd", subject: "docs: explain T-1 in the README" },
    ]);

    expect(progress.done).toBe(1);
    expect(progress.total).toBe(2);
    expect(progress.next?.id).toBe("T-2");
    expect(progress.commitsByTask["T-1"]).toEqual(["aaa"]);
    expect(progress.acs).toEqual([
      { id: "AC-1.1", state: "pending" },
      { id: "AC-1.2", state: "pending" },
      { id: "AC-2.1", state: "done" },
    ]);
    expect(progress.inconsistencies).toEqual([
      "commit bbb cites T-2, but it is not checked",
      "commit ccc cites T-8, not in tasks.md",
    ]);
  });

  it("does not flag checked tasks when the workflow makes no commits", () => {
    const tasks = parseTasks(["- [x] T-1: a", "- [ ] T-2: b"].join("\n"));

    expect(computeProgress([], tasks, []).inconsistencies).toEqual([]);
  });

  it("skips tasks whose dependencies are not done when picking next", () => {
    const tasks = parseTasks(
      ["- [ ] T-1: a", "- [ ] T-2: b", "  - Depends on: T-1"].join("\n"),
    );

    expect(computeProgress([], tasks, []).next?.id).toBe("T-1");
  });
});

describe("handoff zones", () => {
  const tasks = parseTasks(TASKS);
  const progress = computeProgress(parseRequirements(REQUIREMENTS), tasks, [
    { sha: "aaa", subject: "[T-1] table" },
  ]);
  const zone = renderStatusZone(tasks, progress);

  it("renders a status table between markers", () => {
    expect(zone.startsWith(STATUS_ZONE_START)).toBe(true);
    expect(zone.endsWith(STATUS_ZONE_END)).toBe(true);
    expect(zone).toContain("| T-1: Add reset token table | done | aaa |");
    expect(zone).toContain("| T-2: Send reset email | **next** | — |");
  });

  it("assembles narrative + fresh log, then preserves the log byte for byte", () => {
    const first = assembleHandoffBody({
      statusZone: zone,
      narrative: "## Current state\nStarted.\n\n## Log\nmodel junk",
      previousLog: null,
    });

    expect(first).toContain("## Current state\nStarted.");
    expect(first).not.toContain("model junk");

    const log = `${extractLog(first)}\n### 2026-10-07 · T-1: table\n- Commit: aaa`;
    const second = assembleHandoffBody({
      statusZone: zone,
      narrative: "## Current state\nMoving.",
      previousLog: log,
    });

    expect(extractLog(second)).toBe(log);
  });

  it("replaces only the status zone, and refuses without markers", () => {
    const body = `intro\n${zone}\n## Log\nentry`;
    const replaced = replaceStatusZone(
      body,
      `${STATUS_ZONE_START}\nNEW\n${STATUS_ZONE_END}`,
    );

    expect(replaced).toBe(
      `intro\n${STATUS_ZONE_START}\nNEW\n${STATUS_ZONE_END}\n## Log\nentry`,
    );
    expect(replaceStatusZone("no markers", zone)).toBeNull();
  });
});

describe("index state and staleness", () => {
  const record = (
    stage: PlanStageId,
    body: string,
    upstream: string | null,
  ) => ({
    status: "approved" as const,
    generatedAt: "2026-10-07T00:00:00.000Z",
    approvedAt: "2026-10-07T00:00:00.000Z",
    sha: hashDoc(stage, body),
    upstreamSha: upstream,
    mode: "single-shot",
    model: "m",
  });
  const bodies = { requirements: "R1", design: "D1", tasks: "- [ ] T-1: a" };
  const index: PlanIndex = {
    version: 1,
    branch: "feat/x",
    feature: "Reset",
    ticket: null,
    baseRef: "main",
    createdAt: "2026-10-07T00:00:00.000Z",
    updatedAt: "2026-10-07T00:00:00.000Z",
    stages: {
      requirements: record("requirements", "R1", null),
      design: record("design", "D1", hashDoc("requirements", "R1")),
      tasks: record("tasks", bodies.tasks, hashDoc("design", "D1")),
    },
  };

  it("round-trips through index.md and ignores the rendered table", () => {
    const views = computeStageViews(index, bodies);
    const markdown = buildIndexMarkdown({
      index,
      views,
      progress: null,
      coverage: null,
      dirRel: "specs/feat-x",
    });

    expect(parseIndex(markdown)).toEqual(index);
    expect(parseIndex(markdown.replace('"version":1', '"version":2'))).toBe(
      null,
    );
    expect(parseIndex("no state")).toBeNull();
  });

  it("keeps a feature containing --> inside the state comment", () => {
    const tricky = { ...index, feature: 'Ship "a }--> b" safely' };
    const markdown = buildIndexMarkdown({
      index: tricky,
      views: computeStageViews(tricky, bodies),
      progress: null,
      coverage: null,
      dirRel: "specs/feat-x",
    });

    expect(parseIndex(markdown)).toEqual(tricky);
  });

  it("marks approved chains approved and finds the next stage", () => {
    const views = computeStageViews(index, bodies);

    expect(views.requirements.status).toBe("approved");
    expect(views.tasks.status).toBe("approved");
    expect(views.handoff.status).toBe("missing");
    expect(nextStage(views)).toBe("handoff");
  });

  it("ticking a task checkbox is progress, not an edit", () => {
    const views = computeStageViews(index, {
      ...bodies,
      tasks: "- [x] T-1: a",
    });

    expect(views.tasks.editedSinceApproval).toBe(false);
    expect(views.tasks.status).toBe("approved");
  });

  it("an edited requirements body makes everything downstream stale", () => {
    const views = computeStageViews(index, { ...bodies, requirements: "R2" });

    expect(views.requirements.editedSinceApproval).toBe(true);
    expect(views.design.status).toBe("stale");
    expect(views.design.staleBecause).toBe(
      "requirements.md was edited after approval",
    );
    expect(views.tasks.status).toBe("stale");
    expect(nextStage(views)).toBe("requirements");
  });
});

describe("buildLoopPrompt", () => {
  it("points at the plan files and states the stop conditions", () => {
    const prompt = buildLoopPrompt({
      dirRel: "specs/feat-x",
      branch: "feat/x",
      feature: "Reset",
    });

    expect(prompt).toContain("`specs/feat-x/tasks.md`");
    expect(prompt).toContain("[T-n]");
    expect(prompt).toContain("## Spec deltas");
    expect(prompt).toContain("## Stop conditions");
    expect(prompt).toContain("never `git add -A`");
  });
});
