import path from "node:path";
import { describe, expect, it } from "vitest";
import { CLI_DISPLAY_NAME, SINSCRIBE_VERSION } from "../src/constants.js";
import {
  buildPrExportMarkdown,
  getPrExportPath,
  PR_EXPORT_FILENAME,
} from "../src/domain/pr-export.js";

describe("getPrExportPath", () => {
  it("joins the fixed filename onto the repo root", () => {
    expect(getPrExportPath("/repo")).toBe(
      path.join("/repo", "PR_DESCRIPTION.md"),
    );
    expect(PR_EXPORT_FILENAME).toBe("PR_DESCRIPTION.md");
  });
});

describe("buildPrExportMarkdown", () => {
  const input = {
    branch: "feature/login",
    baseRef: "origin/main",
    ticket: "ABC-123",
    templateName: "github",
    description: "## Summary\n\nAdds login.\n",
    generatedAt: new Date("2026-07-09T12:00:00.000Z"),
  };

  it("emits metadata as HTML comments and the description body", () => {
    expect(buildPrExportMarkdown(input)).toBe(
      [
        `<!-- Generated by ${CLI_DISPLAY_NAME} v${SINSCRIBE_VERSION} on 2026-07-09T12:00:00.000Z -->`,
        "<!-- Branch: feature/login · Base: origin/main · Ticket: ABC-123 · Template: github -->",
        "",
        "## Summary",
        "",
        "Adds login.",
        "",
      ].join("\n"),
    );
  });

  it("labels a missing ticket as none", () => {
    expect(buildPrExportMarkdown({ ...input, ticket: null })).toContain(
      "Ticket: none",
    );
  });
});
