import path from "node:path";
import { describe, expect, it } from "vitest";
import { CLI_DISPLAY_NAME, SINSCRIBE_VERSION } from "../src/constants.js";
import {
  buildPromptExportMarkdown,
  getPromptExportPath,
  PROMPT_EXPORT_FILENAME,
} from "../src/domain/prompt-export.js";

describe("getPromptExportPath", () => {
  it("joins the fixed filename onto the repo root", () => {
    expect(getPromptExportPath("/repo")).toBe(
      path.join("/repo", "AGENT_PROMPT.md"),
    );
    expect(PROMPT_EXPORT_FILENAME).toBe("AGENT_PROMPT.md");
  });
});

describe("buildPromptExportMarkdown", () => {
  const input = {
    kind: "feature" as const,
    branch: "feature/login",
    ticket: "ABC-123",
    content: "# Implement retries\n\nRetry uploads.\n",
    generatedAt: new Date("2026-07-10T12:00:00.000Z"),
  };

  it("emits metadata as HTML comments and the prompt body", () => {
    expect(buildPromptExportMarkdown(input)).toBe(
      [
        `<!-- Generated by ${CLI_DISPLAY_NAME} v${SINSCRIBE_VERSION} on 2026-07-10T12:00:00.000Z -->`,
        "<!-- Kind: feature · Branch: feature/login · Ticket: ABC-123 -->",
        "",
        "# Implement retries",
        "",
        "Retry uploads.",
        "",
      ].join("\n"),
    );
  });

  it("labels a missing ticket as none and renders the bugfix kind", () => {
    const markdown = buildPromptExportMarkdown({
      ...input,
      kind: "bugfix",
      ticket: null,
    });

    expect(markdown).toContain("Ticket: none");
    expect(markdown).toContain("Kind: bugfix");
  });
});
