import path from "node:path";
import {
  CLI_DISPLAY_NAME,
  getSinscribeDir,
  SINSCRIBE_VERSION,
} from "../constants.js";

/**
 * Lives under .sinscribe/ and keeps the "project-" prefix anyway, so it can
 * never be mistaken for (or, on case-insensitive filesystems, clobber) a
 * documentation.md the repo keeps itself.
 */
export const DOCS_EXPORT_FILENAME = "project-documentation.md";

export function getDocsExportPath(repoRoot: string): string {
  return path.join(getSinscribeDir(repoRoot), DOCS_EXPORT_FILENAME);
}

export type DocsExportInput = {
  content: string;
  /** Injectable for deterministic tests; defaults to now. */
  generatedAt?: Date;
};

/** Metadata lives in an HTML comment so the document body stays clean. */
export function buildDocsExportMarkdown(input: DocsExportInput): string {
  const generatedAt = (input.generatedAt ?? new Date()).toISOString();

  return [
    `<!-- Generated by ${CLI_DISPLAY_NAME} v${SINSCRIBE_VERSION} on ${generatedAt} -->`,
    "",
    input.content.trimEnd(),
    "",
  ].join("\n");
}
