import path from "node:path";
import { CLI_DISPLAY_NAME, SINSCRIBE_VERSION } from "../constants.js";

/**
 * Deliberately NOT "DOCUMENTATION.md": a repo may already keep a
 * documentation.md, and macOS filesystems are case-insensitive — that
 * name would silently overwrite it.
 */
export const DOCS_EXPORT_FILENAME = "PROJECT_DOCUMENTATION.md";

export function getDocsExportPath(repoRoot: string): string {
  return path.join(repoRoot, DOCS_EXPORT_FILENAME);
}

export type DocsExportInput = {
  content: string;
  /** Injectable for deterministic tests; defaults to now. */
  generatedAt?: Date;
};

/** Metadata lives in an HTML comment so the document body stays clean. */
export function buildDocsExportMarkdown(input: DocsExportInput): string {
  const generatedAt = (input.generatedAt ?? new Date()).toISOString();

  return [
    `<!-- Generated by ${CLI_DISPLAY_NAME} v${SINSCRIBE_VERSION} on ${generatedAt} -->`,
    "",
    input.content.trimEnd(),
    "",
  ].join("\n");
}
