import { readFile } from "node:fs/promises";
import path from "node:path";
import { CLI_DISPLAY_NAME, SINSCRIBE_VERSION } from "../constants.js";
import { isFileNotFoundError } from "../env.js";

/**
 * The steering document a prompting session leaves behind: where the branch
 * stands, what was decided, what is still open. Written at the repo root
 * alongside the other exports so any AI agent finds it without being told.
 */
export const HANDOFF_FILENAME = "HANDOFF.md";

export function getHandoffPath(repoRoot: string): string {
  return path.join(repoRoot, HANDOFF_FILENAME);
}

/** The literal section skeleton the model must emit — everything below the stamped date. */
export const HANDOFF_SECTIONS = `## Where things stand      (the branch's current state: what works, what is half-done)
## What was done this session (concrete changes and decisions made now, not the whole branch history)
## Key decisions           (choices made and the reason, so they are not relitigated)
## Open questions          (unresolved points that need an answer before the work can finish)
## Next steps              (the ordered actions the next session should take first)
## Known issues / blockers (defects, risks, and anything waiting on someone else)`;

const HANDOFF_BLOCKQUOTE = [
  "> Reflects the current state of this branch, not an accumulated history.",
  "> Regenerated at the end of each session.",
].join("\n");

/** Matches the branch recorded in the metadata comment of a previously written file. */
const BRANCH_METADATA = /^<!--\s*Branch:\s*(.+?)\s*(?:·[^>]*)?-->$/mu;

export type HandoffExportInput = {
  /** Repo directory name — the document's title, e.g. "sinscribe". */
  projectName: string;
  branch: string;
  ticket: string | null;
  /** The model-written sections, starting at "## Where things stand". */
  body: string;
  /** Injectable for deterministic tests; defaults to now. */
  generatedAt?: Date;
};

/**
 * Metadata lives in HTML comments and the date is stamped here rather than
 * asked of the model — it cannot know today's date, and the body stays clean.
 */
export function buildHandoffMarkdown(input: HandoffExportInput): string {
  const generatedAt = input.generatedAt ?? new Date();
  const timestamp = generatedAt.toISOString();

  return [
    `<!-- Generated by ${CLI_DISPLAY_NAME} v${SINSCRIBE_VERSION} on ${timestamp} -->`,
    `<!-- Branch: ${input.branch} · Ticket: ${input.ticket ?? "none"} -->`,
    "",
    `# ${input.projectName} — Session Handoff`,
    "",
    HANDOFF_BLOCKQUOTE,
    "",
    "## Last updated",
    timestamp.slice(0, 10),
    "",
    input.body.trim(),
    "",
  ].join("\n");
}

export type ParsedHandoff = {
  /** The branch the file was written on; null when it predates the metadata. */
  branch: string | null;
  /** Everything except the metadata comments, ready to show the model. */
  body: string;
};

/**
 * Splits the leading metadata comments off the readable document. Only the
 * leading run is stripped, so a comment the author added inside the body
 * survives a read/write round trip.
 */
export function parseHandoff(raw: string): ParsedHandoff {
  const branchMatch = BRANCH_METADATA.exec(raw);
  const lines = raw.split("\n");
  let start = 0;

  while (
    start < lines.length &&
    (lines[start].trim().length === 0 ||
      /^<!--.*-->$/u.test(lines[start].trim()))
  ) {
    start += 1;
  }

  return {
    branch: branchMatch ? branchMatch[1] : null,
    body: lines.slice(start).join("\n").trim(),
  };
}

/** Reads the handoff; missing, unreadable, or whitespace-only ⇒ null. */
export async function loadHandoff(
  repoRoot: string | null,
): Promise<ParsedHandoff | null> {
  if (repoRoot === null) {
    return null;
  }

  let raw: string;

  try {
    raw = await readFile(getHandoffPath(repoRoot), "utf8");
  } catch (error) {
    if (isFileNotFoundError(error)) {
      return null;
    }

    throw error;
  }

  const parsed = parseHandoff(raw);

  return parsed.body.length > 0 ? parsed : null;
}
