import { createHash } from "node:crypto";
import path from "node:path";
import {
  CLI_DISPLAY_NAME,
  SINSCRIBE_DIRNAME,
  SINSCRIBE_VERSION,
} from "../constants.js";
import { sanitizeBranchKey } from "../session/store.js";
import { formatStamp } from "../standards/registry.js";

/**
 * The spec plan's pure core: file layout, document framing, hashing and
 * staleness, the requirement/task parsers, coverage and progress. No I/O and
 * no model calls — everything that decides whether a plan is consistent is
 * deterministic and unit-tested here, so the LLM only ever writes prose.
 *
 * The files are the source of truth. Approval lives in index.md (written only
 * by code), never in a conversation or the session JSON: a fresh session, a
 * different agent, or a human reading the repo sees the same state.
 */

export const PLAN_STAGES = [
  "requirements",
  "design",
  "tasks",
  "handoff",
] as const;

export type PlanStageId = (typeof PLAN_STAGES)[number];

export const PLAN_FILES = {
  requirements: "requirements.md",
  design: "design.md",
  tasks: "tasks.md",
  handoff: "handoff.md",
  index: "index.md",
  loop: "loop-prompt.md",
} as const;

export type PlanFileId = keyof typeof PLAN_FILES;

export const STAGE_TITLES: Record<PlanStageId, string> = {
  requirements: "Requirements",
  design: "Design",
  tasks: "Tasks",
  handoff: "Handoff",
};

/**
 * The approved document each stage is generated from. Staleness keys only on
 * the direct upstream: a requirements change makes design stale, which makes
 * tasks stale in turn, so the chain is transitively covered.
 */
export const UPSTREAM: Record<PlanStageId, PlanStageId | null> = {
  requirements: null,
  design: "requirements",
  tasks: "design",
  handoff: "tasks",
};

/** Plans live in .sinscribe/specs/; releases before that used ./specs/. */
export const PLAN_ROOT_DIRNAME = "specs";

export function isPlanStage(value: string): value is PlanStageId {
  return (PLAN_STAGES as readonly string[]).includes(value);
}

/** Repo-relative plan directory, e.g. `.sinscribe/specs/feat-login`. */
export function getPlanDirRel(branch: string): string {
  return `${SINSCRIBE_DIRNAME}/${PLAN_ROOT_DIRNAME}/${sanitizeBranchKey(branch)}`;
}

export function getPlanDir(repoRoot: string, branch: string): string {
  return path.join(repoRoot, ...getPlanDirRel(branch).split("/"));
}

/** Repo-relative pre-.sinscribe/ plan directory, e.g. `specs/feat-login`. */
export function getLegacyPlanDirRel(branch: string): string {
  return `${PLAN_ROOT_DIRNAME}/${sanitizeBranchKey(branch)}`;
}

// ---------------------------------------------------------------------------
// Document framing
// ---------------------------------------------------------------------------

const BODY_START = "<!-- sinscribe:body:start -->";
const BODY_END = "<!-- sinscribe:body:end -->";

const NAV_ORDER: { id: PlanFileId; label: string }[] = [
  { id: "index", label: "Index" },
  { id: "requirements", label: "Requirements" },
  { id: "design", label: "Design" },
  { id: "tasks", label: "Tasks" },
  { id: "handoff", label: "Handoff" },
  { id: "loop", label: "Loop prompt" },
];

/** One-line cross-reference bar; the current document is bold, not linked. */
export function buildNavLine(current: PlanFileId): string {
  return NAV_ORDER.map(({ id, label }) =>
    id === current ? `**${label}**` : `[${label}](${PLAN_FILES[id]})`,
  ).join(" · ");
}

export type PlanDocInput = {
  stage: PlanStageId;
  branch: string;
  feature: string;
  body: string;
  /** Injectable for deterministic tests; defaults to now. */
  generatedAt?: Date;
};

/** The external formats a plan document follows (src/standards/registry.ts). */
const PLAN_STANDARDS = [formatStamp("ears-spec"), formatStamp("spec-kit")].join(
  ", ",
);

/**
 * Frames a model-written body: metadata comments, title and nav are added
 * here (the model cannot know the date and must not invent links), and the
 * body is fenced by markers so its hash ignores the framing.
 */
export function buildPlanDocMarkdown(input: PlanDocInput): string {
  const generatedAt = (input.generatedAt ?? new Date()).toISOString();
  const nav = buildNavLine(input.stage);

  return [
    `<!-- Generated by ${CLI_DISPLAY_NAME} v${SINSCRIBE_VERSION} on ${generatedAt} · standards: ${PLAN_STANDARDS} -->`,
    `<!-- sinscribe-plan-doc: ${input.stage} · Branch: ${input.branch} -->`,
    "",
    `# ${STAGE_TITLES[input.stage]} — ${firstLine(input.feature)}`,
    "",
    `> ${nav}`,
    "",
    BODY_START,
    input.body.trim(),
    BODY_END,
    "",
    "---",
    "",
    `${nav}`,
    "",
  ].join("\n");
}

/**
 * The editable body of a plan document. Uses the markers when present; a
 * file whose markers were deleted by hand falls back to "everything after
 * the leading comments, title and nav", so a human edit never loses content.
 */
export function extractPlanDocBody(raw: string): string {
  const text = raw.replace(/\r\n/gu, "\n");
  const start = text.indexOf(BODY_START);
  const end = text.indexOf(BODY_END);

  if (start !== -1 && end > start) {
    return text.slice(start + BODY_START.length, end).trim();
  }

  const lines = text.split("\n");
  let index = 0;

  while (
    index < lines.length &&
    (lines[index].trim().length === 0 ||
      /^<!--.*-->$/u.test(lines[index].trim()) ||
      /^# /u.test(lines[index]) ||
      /^> .*\]\(index\.md\)/u.test(lines[index]))
  ) {
    index += 1;
  }

  return lines.slice(index).join("\n").trim();
}

/**
 * A short content hash of a stage body. Task checkboxes are normalised
 * before hashing: an agent ticking `[x]` is progress, not a spec change, and
 * must not make the handoff stale or flag tasks.md as hand-edited.
 */
export function hashDoc(stage: PlanStageId, body: string): string {
  let normalised = body.replace(/\r\n/gu, "\n").trim();

  if (stage === "tasks") {
    normalised = normalised.replace(/^(\s*[-*]\s+)\[[xX]\]/gmu, "$1[ ]");
  }

  return createHash("sha256").update(normalised).digest("hex").slice(0, 12);
}

function firstLine(text: string): string {
  const line = text.trim().split("\n")[0]?.trim() ?? "";

  return line.length > 80 ? `${line.slice(0, 77)}...` : line || "Spec plan";
}

// ---------------------------------------------------------------------------
// index.md — state
// ---------------------------------------------------------------------------

export type PlanStageRecord = {
  status: "draft" | "approved";
  generatedAt: string;
  approvedAt: string | null;
  /** hashDoc of the body when it was last written or approved. */
  sha: string;
  /** hashDoc of the upstream body this stage was generated against. */
  upstreamSha: string | null;
  /** How the model gathered context: explored the repo, or single-shot. */
  mode: string;
  model: string;
};

export type PlanIndex = {
  version: 1;
  branch: string;
  feature: string;
  ticket: string | null;
  baseRef: string | null;
  createdAt: string;
  updatedAt: string;
  stages: Partial<Record<PlanStageId, PlanStageRecord>>;
};

export type StageStatus = "missing" | "draft" | "approved" | "stale";

export type StageView = {
  status: StageStatus;
  /** Approved, but the file on disk no longer matches what was approved. */
  editedSinceApproval: boolean;
  staleBecause: string | null;
};

const INDEX_STATE_PATTERN = /<!--\s*sinscribe-plan:\s*(\{[\s\S]*?\})\s*-->/u;

/** Reads only the JSON state comment; a hand-edited table cannot corrupt it. */
export function parseIndex(raw: string): PlanIndex | null {
  const match = INDEX_STATE_PATTERN.exec(raw);

  if (!match) {
    return null;
  }

  let value: unknown;

  try {
    value = JSON.parse(match[1]);
  } catch {
    return null;
  }

  return isPlanIndex(value) ? value : null;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isNullableString(value: unknown): value is string | null {
  return value === null || typeof value === "string";
}

function isStageRecord(value: unknown): value is PlanStageRecord {
  return (
    isRecord(value) &&
    (value.status === "draft" || value.status === "approved") &&
    typeof value.generatedAt === "string" &&
    isNullableString(value.approvedAt) &&
    typeof value.sha === "string" &&
    isNullableString(value.upstreamSha) &&
    typeof value.mode === "string" &&
    typeof value.model === "string"
  );
}

function isPlanIndex(value: unknown): value is PlanIndex {
  if (
    !isRecord(value) ||
    value.version !== 1 ||
    typeof value.branch !== "string" ||
    typeof value.feature !== "string" ||
    !isNullableString(value.ticket) ||
    !isNullableString(value.baseRef) ||
    typeof value.createdAt !== "string" ||
    typeof value.updatedAt !== "string" ||
    !isRecord(value.stages)
  ) {
    return false;
  }

  return Object.entries(value.stages).every(
    ([stage, record]) => isPlanStage(stage) && isStageRecord(record),
  );
}

/**
 * Derives each stage's status from the index records and the bodies on
 * disk. Nothing here is stored: staleness is recomputed from hashes on every
 * read, so a hand edit or a regenerated upstream is always noticed.
 */
export function computeStageViews(
  index: PlanIndex | null,
  bodies: Partial<Record<PlanStageId, string>>,
): Record<PlanStageId, StageView> {
  const views = {} as Record<PlanStageId, StageView>;

  for (const stage of PLAN_STAGES) {
    const record = index?.stages[stage];
    const body = bodies[stage];

    if (!record || body === undefined) {
      views[stage] = {
        status: "missing",
        editedSinceApproval: false,
        staleBecause: null,
      };
      continue;
    }

    // The handoff is a living log the coding agent appends to by design.
    const editedSinceApproval =
      record.status === "approved" &&
      stage !== "handoff" &&
      hashDoc(stage, body) !== record.sha;
    const staleBecause = upstreamProblem(stage, record, bodies, views);

    views[stage] = {
      status:
        staleBecause !== null
          ? "stale"
          : record.status === "approved"
            ? "approved"
            : "draft",
      editedSinceApproval,
      staleBecause,
    };
  }

  return views;
}

function upstreamProblem(
  stage: PlanStageId,
  record: PlanStageRecord,
  bodies: Partial<Record<PlanStageId, string>>,
  views: Record<PlanStageId, StageView>,
): string | null {
  const upstream = UPSTREAM[stage];

  if (upstream === null) {
    return null;
  }

  const upstreamView = views[upstream];
  const upstreamBody = bodies[upstream];
  const upstreamFile = PLAN_FILES[upstream];

  if (upstreamView.status !== "approved" || upstreamBody === undefined) {
    return `${upstreamFile} is not approved`;
  }

  if (upstreamView.editedSinceApproval) {
    return `${upstreamFile} was edited after approval`;
  }

  if (record.upstreamSha !== hashDoc(upstream, upstreamBody)) {
    return `${upstreamFile} changed since this was generated`;
  }

  return null;
}

/** The first stage that still needs work, in pipeline order. */
export function nextStage(
  views: Record<PlanStageId, StageView>,
): PlanStageId | null {
  return (
    PLAN_STAGES.find(
      (stage) =>
        views[stage].status !== "approved" || views[stage].editedSinceApproval,
    ) ?? null
  );
}

// ---------------------------------------------------------------------------
// Parsers
// ---------------------------------------------------------------------------

export type AcceptanceCriterion = { id: string; text: string };

export type Requirement = {
  id: string;
  title: string;
  acs: AcceptanceCriterion[];
};

const REQ_HEADING = /^#{2,4}\s+\**\s*(REQ-\d+)\s*\**\s*[:—–-]?\s*\**\s*(.*)$/u;
const AC_LINE =
  /^\s*[-*]\s+(?:\[[ xX]\]\s+)?\**\s*(AC-\d+(?:\.\d+)?)\s*\**\s*[:—–-]?\s*\**\s*(.*)$/u;

/** `### REQ-n: title` headings, each followed by `- AC-n.m: text` bullets. */
export function parseRequirements(markdown: string): Requirement[] {
  const requirements: Requirement[] = [];
  let current: Requirement | null = null;

  for (const line of markdown.replace(/\r\n/gu, "\n").split("\n")) {
    const heading = REQ_HEADING.exec(line);

    if (heading) {
      current = { id: heading[1], title: cleanText(heading[2]), acs: [] };
      requirements.push(current);
      continue;
    }

    // A new non-REQ heading of the same depth ends the requirement block.
    if (/^#{1,3}\s/u.test(line)) {
      current = null;
      continue;
    }

    const ac = AC_LINE.exec(line);

    if (ac && current) {
      current.acs.push({ id: ac[1], text: cleanText(ac[2]) });
    }
  }

  return requirements;
}

export type TaskSize = "XS" | "S" | "M" | "L" | "XL";

export type PlanTask = {
  id: string;
  title: string;
  done: boolean;
  implements: string[];
  dependsOn: string[];
  files: string[];
  acceptance: string | null;
  verify: string | null;
  size: TaskSize | null;
  /** 0-based line index of the checkbox line in tasks.md. */
  line: number;
};

const TASK_LINE =
  /^\s*[-*]\s+\[([ xX])\]\s+\**\s*(T-\d+)\s*\**\s*[:—–-]?\s*\**\s*(.*)$/u;
const CHECKPOINT_LINE = /^\s*[-*]\s+\[([ xX])\]\s+\**\s*Checkpoint\b/iu;
const FIELD_LINE = /^\s+[-*]\s+\**\s*([A-Za-z ]+?)\s*\**\s*:\s*\**\s*(.*)$/u;
const AC_ID = /\bAC-\d+(?:\.\d+)?\b/gu;
const TASK_ID = /\bT-\d+\b/gu;
/** The loop's commit convention: `[T-n]` in the subject, nothing looser. */
const COMMIT_TASK_ID = /\[(T-\d+)\]/gu;

/**
 * `- [ ] T-n: title` lines with indented `- Field: value` sub-bullets.
 * Tolerant of bold markers and `[X]`, because an external agent edits this
 * file and small formatting drift must not lose its progress.
 */
export function parseTasks(markdown: string): PlanTask[] {
  const tasks: PlanTask[] = [];
  let current: PlanTask | null = null;
  const lines = markdown.replace(/\r\n/gu, "\n").split("\n");

  lines.forEach((line, lineIndex) => {
    const task = TASK_LINE.exec(line);

    if (task) {
      current = {
        id: task[2],
        title: cleanText(task[3]),
        done: task[1] !== " ",
        implements: [],
        dependsOn: [],
        files: [],
        acceptance: null,
        verify: null,
        size: null,
        line: lineIndex,
      };
      tasks.push(current);
      return;
    }

    if (CHECKPOINT_LINE.test(line) || /^\S/u.test(line)) {
      current = null;
      return;
    }

    const field = FIELD_LINE.exec(line);

    if (field && current) {
      applyTaskField(current, field[1].toLowerCase(), field[2]);
    }
  });

  return tasks;
}

function applyTaskField(task: PlanTask, name: string, value: string): void {
  const text = cleanText(value);

  if (name.startsWith("implement")) {
    task.implements = unique(text.match(AC_ID) ?? []);
  } else if (name.startsWith("depend")) {
    task.dependsOn = unique(text.match(TASK_ID) ?? []);
  } else if (name.startsWith("file")) {
    task.files = text
      .split(",")
      .map((file) => file.replace(/`/gu, "").trim())
      .filter((file) => file.length > 0 && !/^none$/iu.test(file));
  } else if (name.startsWith("acceptance")) {
    task.acceptance = text || null;
  } else if (name.startsWith("verify")) {
    task.verify = text.replace(/^`+|`+$/gu, "").trim() || null;
  } else if (name.startsWith("size")) {
    const size = /\b(XL|XS|S|M|L)\b/u.exec(text.toUpperCase());

    task.size = size ? (size[1] as TaskSize) : null;
  }
}

/** Checkpoint lines in tasks.md: `- [ ] Checkpoint: …`. */
export function countCheckpoints(markdown: string): {
  total: number;
  done: number;
} {
  let total = 0;
  let done = 0;

  for (const line of markdown.split("\n")) {
    const match = CHECKPOINT_LINE.exec(line);

    if (match) {
      total += 1;
      done += match[1] === " " ? 0 : 1;
    }
  }

  return { total, done };
}

function cleanText(text: string): string {
  return text.replace(/\*\*/gu, "").trim();
}

function unique(values: string[]): string[] {
  return [...new Set(values)];
}

// ---------------------------------------------------------------------------
// Coverage — the traceability check agent-skills leaves to prose
// ---------------------------------------------------------------------------

/** Tasks touching more files than this should be split (agent-skills' M). */
export const MAX_TASK_FILES = 5;

export type CoverageReport = {
  /** Block approval: the plan references things that do not exist. */
  errors: string[];
  /** Shown and recorded, but approval is allowed. */
  warnings: string[];
  uncoveredAcs: string[];
  totalAcs: number;
};

export function computeCoverage(
  requirements: Requirement[],
  tasks: PlanTask[],
): CoverageReport {
  const errors: string[] = [];
  const warnings: string[] = [];
  const acIds = requirements.flatMap((req) => req.acs.map((ac) => ac.id));
  const knownAcs = new Set(acIds);
  const taskIds = new Set<string>();

  for (const id of duplicates(acIds)) {
    errors.push(`${id} is defined more than once in requirements.md`);
  }

  for (const id of duplicates(tasks.map((task) => task.id))) {
    errors.push(`${id} is defined more than once in tasks.md`);
  }

  for (const task of tasks) {
    taskIds.add(task.id);
  }

  if (acIds.length === 0) {
    warnings.push("no AC-n.m acceptance criteria found in requirements.md");
  }

  if (tasks.length === 0) {
    errors.push("no `- [ ] T-n: …` tasks found in tasks.md");
  }

  const covered = new Set<string>();

  for (const task of tasks) {
    for (const ac of task.implements) {
      if (knownAcs.has(ac)) {
        covered.add(ac);
      } else {
        errors.push(`${task.id} implements ${ac}, which requirements.md lacks`);
      }
    }

    for (const dep of task.dependsOn) {
      if (!taskIds.has(dep)) {
        errors.push(`${task.id} depends on ${dep}, which does not exist`);
      } else if (dep === task.id) {
        errors.push(`${task.id} depends on itself`);
      }
    }

    if (task.implements.length === 0) {
      warnings.push(`${task.id} does not name the AC it implements`);
    }

    if (task.verify === null) {
      warnings.push(`${task.id} has no Verify command`);
    }

    if (
      task.size === "L" ||
      task.size === "XL" ||
      task.files.length > MAX_TASK_FILES
    ) {
      warnings.push(
        `${task.id} is too large (${task.size ?? `${task.files.length} files`}) — split it`,
      );
    }
  }

  for (const cycle of findCycles(tasks)) {
    errors.push(`dependency cycle: ${cycle.join(" → ")}`);
  }

  const uncoveredAcs = acIds.filter((id) => !covered.has(id));

  if (uncoveredAcs.length > 0) {
    warnings.push(`no task implements ${uncoveredAcs.join(", ")}`);
  }

  return {
    errors: unique(errors),
    warnings: unique(warnings),
    uncoveredAcs,
    totalAcs: acIds.length,
  };
}

function duplicates(values: string[]): string[] {
  const seen = new Set<string>();
  const repeated = new Set<string>();

  for (const value of values) {
    if (seen.has(value)) {
      repeated.add(value);
    }

    seen.add(value);
  }

  return [...repeated];
}

function findCycles(tasks: PlanTask[]): string[][] {
  // Duplicate ids (already an error) merge their edges rather than hiding them.
  const deps = new Map<string, string[]>();

  for (const task of tasks) {
    deps.set(task.id, [...(deps.get(task.id) ?? []), ...task.dependsOn]);
  }
  const state = new Map<string, "visiting" | "done">();
  const cycles: string[][] = [];

  const visit = (id: string, trail: string[]): void => {
    if (state.get(id) === "done") {
      return;
    }

    if (state.get(id) === "visiting") {
      cycles.push([...trail.slice(trail.indexOf(id)), id]);
      return;
    }

    state.set(id, "visiting");

    for (const dep of deps.get(id) ?? []) {
      if (deps.has(dep) && dep !== id) {
        visit(dep, [...trail, id]);
      }
    }

    state.set(id, "done");
  };

  for (const task of tasks) {
    visit(task.id, []);
  }

  return cycles;
}

/**
 * Re-applies `[x]` to regenerated tasks that keep their id, so revising the
 * plan mid-implementation does not erase progress. Done tasks that vanished
 * are reported: their work exists in git but no longer in the plan.
 */
export function preserveTaskState(
  previous: PlanTask[],
  nextMarkdown: string,
): { markdown: string; dropped: string[] } {
  const done = new Set(
    previous.filter((task) => task.done).map((task) => task.id),
  );
  const seen = new Set<string>();
  const markdown = nextMarkdown
    .split("\n")
    .map((line) => {
      const match = TASK_LINE.exec(line);

      if (!match) {
        return line;
      }

      seen.add(match[2]);

      return done.has(match[2]) ? line.replace(/\[[ xX]\]/u, "[x]") : line;
    })
    .join("\n");

  return { markdown, dropped: [...done].filter((id) => !seen.has(id)) };
}

// ---------------------------------------------------------------------------
// Progress — what the loop has actually done
// ---------------------------------------------------------------------------

export type AcState = "done" | "partial" | "uncovered" | "pending";

export type ProgressReport = {
  done: number;
  total: number;
  next: PlanTask | null;
  acs: { id: string; state: AcState }[];
  commitsByTask: Record<string, string[]>;
  /** Plan and git disagree — worth a human look. */
  inconsistencies: string[];
};

export function computeProgress(
  requirements: Requirement[],
  tasks: PlanTask[],
  commits: { sha: string; subject: string }[],
): ProgressReport {
  const byId = new Map(tasks.map((task) => [task.id, task]));
  const commitsByTask: Record<string, string[]> = {};
  const inconsistencies: string[] = [];

  for (const commit of commits) {
    const ids = [...commit.subject.matchAll(COMMIT_TASK_ID)].map(
      (match) => match[1],
    );

    for (const id of unique(ids)) {
      (commitsByTask[id] ??= []).push(commit.sha);
    }
  }

  for (const [id, shas] of Object.entries(commitsByTask)) {
    const task = byId.get(id);

    if (!task) {
      inconsistencies.push(`commit ${shas[0]} cites ${id}, not in tasks.md`);
    } else if (!task.done) {
      inconsistencies.push(
        `commit ${shas[0]} cites ${id}, but it is not checked`,
      );
    }
  }

  // Only a commit-based workflow expects a commit per task: when no commit
  // cites any task (e.g. the rules say "do not commit"), silence is normal.
  if (Object.keys(commitsByTask).length > 0) {
    for (const task of tasks) {
      if (task.done && !commitsByTask[task.id]) {
        inconsistencies.push(`${task.id} is checked but no commit cites it`);
      }
    }
  }

  const next =
    tasks.find(
      (task) =>
        !task.done &&
        task.dependsOn.every((dep) => byId.get(dep)?.done ?? true),
    ) ?? null;

  const acs = requirements.flatMap((req) =>
    req.acs.map((ac) => {
      const implementing = tasks.filter((task) =>
        task.implements.includes(ac.id),
      );
      const doneCount = implementing.filter((task) => task.done).length;
      const state: AcState =
        implementing.length === 0
          ? "uncovered"
          : doneCount === implementing.length
            ? "done"
            : doneCount > 0
              ? "partial"
              : "pending";

      return { id: ac.id, state };
    }),
  );

  return {
    done: tasks.filter((task) => task.done).length,
    total: tasks.length,
    next,
    acs,
    commitsByTask,
    inconsistencies,
  };
}

export function summarizeProgress(progress: ProgressReport): string {
  const acsDone = progress.acs.filter((ac) => ac.state === "done").length;
  const next = progress.next ? ` · next ${progress.next.id}` : "";

  return (
    `tasks ${progress.done}/${progress.total} · ` +
    `ACs ${acsDone}/${progress.acs.length} done${next}`
  );
}

// ---------------------------------------------------------------------------
// handoff.md — code-owned zones around the model's narrative
// ---------------------------------------------------------------------------

export const STATUS_ZONE_START = "<!-- sinscribe:status:start -->";
export const STATUS_ZONE_END = "<!-- sinscribe:status:end -->";
export const LOG_HEADING = "## Log";

const LOG_INTRO = [
  "<!-- Append-only. One entry per task, newest last:",
  "### <date> · T-n: <title>",
  "- Changed: <files and what changed>",
  "- Verify: `<command>` → <pass|fail + key output>",
  "- Commit: <sha>",
  "- Notes: <decisions, surprises, follow-ups> -->",
].join("\n");

/** The code-owned status zone at the top of handoff.md: one row per task. */
export function renderStatusZone(
  tasks: PlanTask[],
  progress: ProgressReport,
): string {
  const lines = [STATUS_ZONE_START, "## Status", ""];

  if (tasks.length === 0) {
    lines.push("_No tasks yet — approve tasks.md first._");
  } else {
    lines.push(`**${summarizeProgress(progress)}**`, "");
    lines.push("| Task | State | Commits |", "| --- | --- | --- |");

    for (const task of tasks) {
      const state = task.done
        ? "done"
        : progress.next?.id === task.id
          ? "**next**"
          : "todo";
      const commits = (progress.commitsByTask[task.id] ?? []).join(", ");

      lines.push(
        `| ${task.id}: ${task.title} | ${state} | ${commits || "—"} |`,
      );
    }
  }

  lines.push(STATUS_ZONE_END);

  return lines.join("\n");
}

/** Replaces the status zone; null when its markers are missing (refuse). */
export function replaceStatusZone(
  handoff: string,
  zone: string,
): string | null {
  const start = handoff.indexOf(STATUS_ZONE_START);
  const end = handoff.indexOf(STATUS_ZONE_END);

  if (start === -1 || end < start) {
    return null;
  }

  return (
    handoff.slice(0, start) + zone + handoff.slice(end + STATUS_ZONE_END.length)
  );
}

/** Everything from `## Log` to the end of the body; the log is never regenerated. */
export function extractLog(handoffBody: string): string | null {
  const match = /^## Log\s*$/mu.exec(handoffBody);

  return match ? handoffBody.slice(match.index).trim() : null;
}

/**
 * Assembles the handoff body: code-owned status zone, the model's narrative
 * (with any `## Log` it wrote dropped), then the preserved log — or a fresh
 * one with the entry template.
 */
export function assembleHandoffBody(input: {
  statusZone: string;
  narrative: string;
  previousLog: string | null;
}): string {
  const logStart = /^## Log\s*$/mu.exec(input.narrative)?.index;
  const narrative = input.narrative.slice(0, logStart).trim();
  const log = input.previousLog ?? `${LOG_HEADING}\n\n${LOG_INTRO}`;

  return [input.statusZone, "", narrative, "", log].join("\n").trim();
}

// ---------------------------------------------------------------------------
// index.md rendering
// ---------------------------------------------------------------------------

export function buildIndexMarkdown(input: {
  index: PlanIndex;
  views: Record<PlanStageId, StageView>;
  progress: ProgressReport | null;
  coverage: CoverageReport | null;
  dirRel: string;
  generatedAt?: Date;
}): string {
  const { index, views, progress, coverage, dirRel } = input;
  const generatedAt = (input.generatedAt ?? new Date()).toISOString();
  const rows = PLAN_STAGES.map((stage, position) => {
    const view = views[stage];
    const record = index.stages[stage];
    const status =
      view.status === "stale"
        ? `stale (${view.staleBecause ?? "upstream changed"})`
        : view.editedSinceApproval
          ? "approved · edited since"
          : view.status;

    return (
      `| ${position + 1} | ${STAGE_TITLES[stage]} | ` +
      `[${PLAN_FILES[stage]}](${PLAN_FILES[stage]}) | ${status} | ` +
      `${record?.approvedAt?.slice(0, 10) ?? "—"} | ${record?.mode ?? "—"} |`
    );
  });
  const progressLines =
    progress === null || progress.total === 0
      ? ["_Tasks are not approved yet._"]
      : [
          `- ${summarizeProgress(progress)}`,
          ...(coverage && coverage.uncoveredAcs.length > 0
            ? [`- Uncovered: ${coverage.uncoveredAcs.join(", ")}`]
            : []),
          ...progress.inconsistencies
            .slice(0, 5)
            .map((issue) => `- ⚠ ${issue}`),
        ];

  return [
    `<!-- Generated by ${CLI_DISPLAY_NAME} v${SINSCRIBE_VERSION} on ${generatedAt} -->`,
    // ">" only occurs inside JSON strings, and \u003e parses back to it, so a
    // feature such as "a }--> b" cannot end the comment early.
    `<!-- sinscribe-plan: ${JSON.stringify(index).replace(/>/gu, "\\u003e")} -->`,
    "<!-- Written by Sinscribe only. Edit the stage files, not this one. -->",
    "",
    `# ${firstLine(index.feature)} — Spec plan`,
    "",
    `> ${buildNavLine("index")}`,
    "",
    `Branch \`${index.branch}\` · Ticket ${index.ticket ?? "none"} · ` +
      `Base ${index.baseRef ? `\`${index.baseRef}\`` : "unknown"}`,
    "",
    "## Stages",
    "",
    "| # | Stage | File | Status | Approved | Context |",
    "| --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
    "## Progress",
    "",
    ...progressLines,
    "",
    "## How to resume",
    "",
    "- Humans: run `sinscribe plan` (menu → Spec plan) to continue, regenerate a stage, or sync progress.",
    `- Coding agents: start at [${PLAN_FILES.loop}](${PLAN_FILES.loop}) — or \`sinscribe plan --loop-prompt\`.`,
    "- After commits land: `sinscribe plan --sync` refreshes the status here and in handoff.md.",
    "",
    "## Loop contract",
    "",
    "1. One task at a time, in dependency order — the first unchecked task whose dependencies are checked.",
    "2. A task is done only when its Verify command passes; then tick it and — unless the project's rules forbid commits — commit it with `[T-n]` in the subject.",
    "3. Every task appends an entry to the handoff log.",
    "4. Requirements and design are never edited by the agent — it records a spec delta and stops.",
    "5. Stop at checkpoints, on blockers, and after three failed attempts.",
    "6. Finished means every task is checked **and** every AC is verified.",
    "",
    `<!-- Plan directory: ${dirRel} -->`,
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// loop-prompt.md — the operating contract for the coding agent
// ---------------------------------------------------------------------------

export function buildLoopPrompt(input: {
  dirRel: string;
  branch: string;
  feature: string;
  generatedAt?: Date;
}): string {
  const generatedAt = (input.generatedAt ?? new Date()).toISOString();
  const dir = input.dirRel;

  return [
    `<!-- Generated by ${CLI_DISPLAY_NAME} v${SINSCRIBE_VERSION} on ${generatedAt} -->`,
    `<!-- sinscribe-plan-doc: loop · Branch: ${input.branch} -->`,
    "",
    `# Implementation loop — ${firstLine(input.feature)}`,
    "",
    `> ${buildNavLine("loop")}`,
    "",
    `You are implementing an approved spec plan on branch \`${input.branch}\`.`,
    `The plan lives in \`${dir}/\`. The files are the source of truth — not this`,
    "conversation, not your memory of a previous session.",
    "",
    "## 0. Orient (every time you start or resume)",
    "",
    `1. Read, in order: \`${dir}/index.md\`, \`${dir}/requirements.md\`,`,
    `   \`${dir}/design.md\`, \`${dir}/tasks.md\`, \`${dir}/handoff.md\`.`,
    "2. Run `git status` and `git log --oneline -15`. If the working tree has",
    "   changes that no task explains, stop and ask before touching anything.",
    "3. Read the project's own rules (CLAUDE.md, AGENTS.md, CONTRIBUTING) and use",
    "   its real commands — never assume `npm test`.",
    "4. If index.md shows any stage as stale or not approved, stop: the plan",
    "   must be re-approved in Sinscribe (`sinscribe plan`) before you build.",
    "",
    "## 1. The loop",
    "",
    "Repeat until every task in tasks.md is checked:",
    "",
    "1. **Pick** the first unchecked `T-n` whose `Depends on` tasks are all checked.",
    "   Write it under `## Current task` in handoff.md.",
    "2. **Plan** in at most three lines: the files you will touch and how you",
    "   will prove it works. Touch only the task's `Files` unless the task is",
    "   impossible without another file — then say so in the log.",
    "3. **Test first** where the stack allows: write or extend a test for the",
    "   task's Acceptance and the ACs it Implements; see it fail.",
    "4. **Implement** the minimum that makes it pass. No drive-by refactors.",
    "5. **Verify**: run the task's exact `Verify` command, then the project's",
    "   broader test/build/lint gates. Read the output; do not assume.",
    "6. **On pass**: tick the task `[x]` in tasks.md and append a `## Log` entry",
    "   to handoff.md (changed · verify command → result · commit · notes). Then",
    "   commit: stage only the files this task touched plus tasks.md/handoff.md",
    "   (never `git add -A`), with `[T-n]` in the subject. **If the project's or",
    "   user's rules say not to commit, do not commit** — leave the change in the",
    "   working tree and write `Commit: uncommitted` in the log entry.",
    "7. **On fail**: diagnose the root cause and retry — at most three attempts.",
    "   Then record it under `## Blockers` in handoff.md and **stop**.",
    "8. **Checkpoint**: when you reach an unchecked `- [ ] Checkpoint` line, run",
    "   the full gates, summarise progress, and **stop** for human review. The",
    "   human ticks the checkpoint.",
    "",
    "## 2. Feedback into the spec (never edit it silently)",
    "",
    "- requirements.md and design.md are **read-only** for you.",
    "- If the code contradicts the design, a requirement is ambiguous, or a",
    "  needed decision is not covered: write it under `## Spec deltas` in",
    "  handoff.md (what, why, options A/B/C, your recommendation) and **stop**.",
    "  The human updates the spec in Sinscribe; regenerated tasks keep their ids",
    "  and checkmarks.",
    "- Things you notice outside the task's scope go under",
    "  `## Noticed but not touching` — do not fix them now.",
    "",
    "## 3. Finish",
    "",
    "When every task is checked:",
    "",
    "1. Walk every `AC-n.m` in requirements.md. For each, cite the test or the",
    "   command that proves it, and run it. Record the results in the log as",
    "   `### AC verification`.",
    "2. Any AC you cannot prove is not done. Do **not** add tasks to tasks.md",
    "   yourself — any edit beyond a checkbox makes the plan stale. Write it under",
    "   `## Spec deltas` in handoff.md (the AC, why it is unproven, the task you",
    "   propose) and stop; the human regenerates tasks in Sinscribe.",
    "3. Finish with a summary: tasks completed, commits, tests added, open spec",
    "   deltas, and anything left for the human. Then tell the human to run",
    "   `sinscribe plan --sync`.",
    "",
    "## Stop conditions — stop and report instead of pushing on",
    "",
    "- A Verify command fails three times, or the build breaks with no obvious fix.",
    "- A task needs a decision the spec does not cover (→ spec delta).",
    "- An unchecked checkpoint is reached.",
    "- The change is risky or irreversible: auth/permissions, data migrations,",
    "  deletions, payments, secrets, deploys — get explicit sign-off first.",
    "- Unexplained local changes, or the plan is stale.",
    "",
    "## Red flags — if you catch yourself thinking these, stop",
    "",
    "| Thought | Reality |",
    "| --- | --- |",
    '| "This test is flaky, I\'ll skip it" | A skipped check is an unverified task. Record a blocker. |',
    '| "I\'ll tick it now and verify later" | Done means verified. Unverified work is not done. |',
    "| \"While I'm here I'll also fix…\" | Scope creep. Log it under Noticed but not touching. |",
    '| "The spec is obviously wrong, I\'ll adjust it" | Write a spec delta and stop. The human owns the spec. |',
    '| "I\'ll batch these three tasks into one commit" | One task, one commit — every point stays revertable (when committing is allowed). |',
    '| "It passed before, no need to re-run" | Re-run when the code has moved since. |',
    "",
  ].join("\n");
}
