import path from "node:path";
import { CLI_DISPLAY_NAME, SINSCRIBE_VERSION } from "../constants.js";

export const PR_EXPORT_FILENAME = "PR_DESCRIPTION.md";

export function getPrExportPath(repoRoot: string): string {
  return path.join(repoRoot, PR_EXPORT_FILENAME);
}

export type PrExportInput = {
  branch: string;
  baseRef: string;
  ticket: string | null;
  templateName: string;
  description: string;
  /** Injectable for deterministic tests; defaults to now. */
  generatedAt?: Date;
};

/**
 * Builds the exported markdown. Metadata lives in HTML comments so the body
 * stays paste-ready for GitHub/GitLab without a header polluting the PR.
 */
export function buildPrExportMarkdown(input: PrExportInput): string {
  const generatedAt = (input.generatedAt ?? new Date()).toISOString();

  return [
    `<!-- Generated by ${CLI_DISPLAY_NAME} v${SINSCRIBE_VERSION} on ${generatedAt} -->`,
    `<!-- Branch: ${input.branch} · Base: ${input.baseRef} · Ticket: ${input.ticket ?? "none"} · Template: ${input.templateName} -->`,
    "",
    input.description.trimEnd(),
    "",
  ].join("\n");
}
