import path from "node:path";
import { CLI_DISPLAY_NAME, SINSCRIBE_VERSION } from "../constants.js";

export const PROMPT_EXPORT_FILENAME = "AGENT_PROMPT.md";

export function getPromptExportPath(repoRoot: string): string {
  return path.join(repoRoot, PROMPT_EXPORT_FILENAME);
}

export type PromptExportInput = {
  kind: "feature" | "bugfix";
  branch: string;
  ticket: string | null;
  content: string;
  /** Injectable for deterministic tests; defaults to now. */
  generatedAt?: Date;
};

/**
 * Builds the exported markdown. Metadata lives in HTML comments so the body
 * stays paste-ready for any AI agent's input box.
 */
export function buildPromptExportMarkdown(input: PromptExportInput): string {
  const generatedAt = (input.generatedAt ?? new Date()).toISOString();

  return [
    `<!-- Generated by ${CLI_DISPLAY_NAME} v${SINSCRIBE_VERSION} on ${generatedAt} -->`,
    `<!-- Kind: ${input.kind} · Branch: ${input.branch} · Ticket: ${input.ticket ?? "none"} -->`,
    "",
    input.content.trimEnd(),
    "",
  ].join("\n");
}
